### ISSUE TITLE
phpBB 3.2

### ISSUE THREAD

**Issue by ghost** [ForumHulp/helper#4]
Are you planning on updating this for use with phpBB 3.2?

**Comment by ForumHulp** [comment]
This version should run fine on phpbb 3.2

**Comment by ghost** [comment]
m1_initial_file.php causes issues because it's trying to overwrite core files that already contain the changes, although the code included in acp_extensions is not totally identical to what m1_initial_file.php searches for.

Delete m1_initial_file.php and it does indeed work.

**Comment by ForumHulp** [comment]
You are right, the event is added to the core
