### ISSUE TITLE
Problem after removal

### ISSUE THREAD

**Issue by jackennils** [ForumHulp/helper#5]
Hello!

I have installed the Helper extension together with Email on Birthday. As it was not what I have expected, I wanted to remove both of them. So I deactivated them, removed all work files and then deleted them from the server via FTP.

But now I cannot access the ACP module of the Extensions anymore, getting a Error 500.

Here's the excerpt from the error log of my server:
```
PHP Fatal error:  Uncaught Error: Call to a member function trigger_event() on null in /mnt/web216/d0/96/54287996/htdocs/web/httpdocs/forum/includes/acp/acp_extensions.php:75
Stack trace:
#0 /mnt/web216/d0/96/54287996/htdocs/web/httpdocs/forum/includes/functions_module.php(676): acp_extensions->main('extensions', 'main')
#1 /mnt/web216/d0/96/54287996/htdocs/web/httpdocs/forum/adm/index.php(82): p_master->load_active()
#2 {main}
thrown in /mnt/web216/d0/96/54287996/htdocs/web/httpdocs/forum/includes/acp/acp_extensions.php on line 75
```

Please help!

Thanks
Nils

**Comment by Galixte** [comment]
Hi @ForumHulp,

could you take a look, please ?

**Comment by jackennils** [comment]
I found out that the extension is modifying the core file (acp_extensions). Fortunately there's a backup file in the folder which could be restored and the error is gone.

Anyway, as extensions are not allowed to modify the core, I will avoid using forumhulp extensions in the future.

**Comment by ForumHulp** [comment]
You should disable and run delete data in order to put your files back in original state as all the instructions are telling.

**Comment by ForumHulp** [comment]
Solved
