### ISSUE TITLE
Fatal error: After uninstalling extension (last version from may 2017)

### ISSUE THREAD

**Issue by Galixte** [ForumHulp/helper#7]
Hi @ForumHulp ,

i think this extension has a problem with uninstalling process because on a vanilla installation of phpBB 3.2.0, if i want to uninstall this extension by desactivate extension, then delete data, i have this error message:

[phpBB Debug] PHP Notice: in file [ROOT]/includes/acp/acp_extensions.php on line 49: Undefined variable: phpbb_dispatcher

( ! ) Fatal error: Call to a member function trigger_event() on null in \phpBB320\includes\acp\acp_extensions.php on line 75
Call Stack
#	Time	Memory	Function	Location
1	0.0005	152576	{main}( )	...\index.php:0
2	2.9001	13413144	p_master->load_active( )	...\index.php:82
3	2.9013	13516864	acp_extensions->main( )	...\functions_module.php:676

**Comment by Galixte** [comment]
> vanilla

sh

**Comment by ForumHulp** [comment]
The event is in core file now so it's not needed to add it anymore

**Comment by Galixte** [comment]
Hi @ForumHulp,

the event you think about, what is his name ? It’s in the phpBB core since which version of phpBB ? 3.2.1 ? 3.2.0 ?

I have tested your 3.1.11 version, i noticed that the phpBB file: ```./includes/acp/acp_extensions.php``` isn’t modified anymore by your extension like 3.1.10, good news !
