### ISSUE TITLE
Update to 3.1.11 on this repository contains some errors

### ISSUE THREAD

**Issue by Galixte** [ForumHulp/helper#8]
Hi @ForumHulp,

thanks to update to 3.1.11, but there are some errors (duplicates files & folders from 3.1.10 version), see that folder inside: https://github.com/ForumHulp/helper/tree/master/helper it should be deleted, i think.

Futhermore, i will fix my FRENCH translation because in FRENCH we have a non-breaking space before some characters like ```:```, ```;```, ```?```, ```!``` & after ```«``` an before ```»```

**Comment by Galixte** [comment]
I suggest you this PR: https://github.com/ForumHulp/helper/pull/10.

**Comment by ForumHulp** [comment]
Thanks Galixte, you are right, Must be a coy error or something
